### ISSUE TITLE
question about enforcing disentanglement of shape and style

### ISSUE THREAD

**Issue by gene-chou** [mihirp1998/Disentangling-3D-Prototypical-Nets#1]
Thanks for your work! I was wondering how you enforced disentanglement of shape and style. Your cycle consistency loss ensures that latent codes are disentangled in the same way, but that doesn't imply separation of shape and style?

**Comment by mihirp1998** [comment]
We use adaptive instance normalization for style/shape disentanglement:
Code ref:
https://github.com/mihirp1998/Disentangling-3D-Prototypical-Nets/blob/74cc0b2548a6c02591685320e72934c902a1c413/archs/munit_modules_3d.py#L515
Paper ref: https://arxiv.org/abs/1703.06868

There is an asymmetry in this function which results in style/shape
disentanglement. Cyclic consistency simply reinforces this loss.

**Comment by gene-chou** [comment]
got it, thank you :)
